services:
    app:
        build:
            context: .
            args:
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
                DEV: ${DEV:-true}
            dockerfile: docker/Dockerfile
        environment:
            FASTAPI_CONFIG_PATH: /src/app.conf
        volumes:
            - ./:/src
            - ./secrets:/src/secrets
        ports:
            - 8577:8577
        extra_hosts:
            - "host.docker.internal:host-gateway"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8577/health"]
            interval: 1m
            start_period: 30s

    syslog:
        image: balabit/syslog-ng:latest
        ports:
            - "5514:5514/udp" # App logs
            - "5515:5515/udp" # SIEM
            - "5516:5516/udp" # Public inspection
            - "5517:5517/udp" # Debug
        volumes:
            - ./docker/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
            - ./logs:/var/log/app
